# Generated by Django 6.0.4 on 2026-04-16 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tutoring', 'Tutoring'), ('design', 'Design'), ('coding', 'Coding'), ('other', 'Other')], max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if the skill is free.', max_digits=7, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('chat', 'Chat / DM'), ('phone', 'Phone')], max_length=20)),
                ('availability_status', models.CharField(choices=[('open', 'Open'), ('busy', 'Busy'), ('away', 'Away')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
